apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: clinicmanagementapi
  name: clinicmanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clinicmanagementapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: clinicmanagementapi
    spec:
      containers:
        - image: clinicmanagementapi
          name: clinicmanagementapi
          ports:
            - containerPort: 443
          resources: {}
      restartPolicy: Always
status: {}
