apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: clinicmanagement-db
  name: clinicmanagement-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clinicmanagement-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: clinicmanagement-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "1"
            - name: MSSQL_SA_PASSWORD
              value: P@ssW0rd!
          image: mcr.microsoft.com/azure-sql-edge:latest
          name: clinicmanagement-db
          ports:
            - containerPort: 1433
          resources: {}
      restartPolicy: Always
status: {}
