version: '3.4'

services:
  clinicmanagement-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: ddd.clinicmanagement-db
    environment:
      MSSQL_SA_PASSWORD: 'P@ssW0rd!'
      ACCEPT_EULA: '1'
    ports:
      - "1433:1433"
  prometheus-monitor:
    image: ubuntu/prometheus
    container_name: ddd.clinicmanagement-mon
    ports:
      - "30090:9090"
  #clinicmanagementblazor:
   #image: ${DOCKER_REGISTRY-}clinicmanagementblazor
   #build:
   #  context: .
   #  dockerfile: src/ClinicManagement.Blazor.Host/Dockerfile
  clinicmanagementapi:
    image: ${DOCKER_REGISTRY-}clinicmanagementapi
    build:
      context: .
      dockerfile: src/ClinicManagement.Api/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - clinicmanagement-db
